#!/bin/bash

# semver's installer
install() {
	local repo="$(dirname $(find "$HOME" -type d -name .semver 2>/dev/null | grep repo))"
	cp -f "$repo"/semver "$HOME"/bin || return
	cp -f "$repo"/.semver/.lib "$HOME"/.semver || return
	cp -f "$repo"/.semver/help "$HOME"/.semver || return
	cp -f "$repo"/.semver/version "$HOME"/.semver || return
	[[ ! -e "$HOME/.semver/.cfg" ]] && { cp -f "$repo"/.semver/.cfg "$HOME"/.semver/.cfg || return 1; }
	echo "semver installed!"
}

install
