#!/bin/sh

# Grab the repo path just in case
repo="$(grep 'repo_path' "$HOME/.semver/app.cfg" | cut -d= -f2)"

# Remove ${s_appname} from the system
rm -rf "$HOME/.semver"
rm "$HOME/bin/semver"

# Ask if the user would like to remove the repo
printf "Would you like to remove the repo as well? [Y/n] "
read -r yn
yn="$(echo "$yn" | tr '[:upper:]' '[:lower:]')"
[ "$yn" = 'y' ] && rm -rf "$repo"

# Let the user know that all of ${s_appname}'s files have been removed
echo "All of semver's files have been removed."